[package]
name = "rd-std"
version = "0.1.0"
authors = ["spacemeowx2 <spacemeowx2@gmail.com>"]
edition = "2018"
description = "std for rabbit-digger"
license = "MIT OR Apache-2.0"

[dependencies]
# common
rd-interface = { version = "0.4", path = "../rd-interface" }
rd-derive = { version = "0.1", path = "../rd-derive" }
futures = "0.3"
serde = "1.0"
tracing = "0.1.26"
thiserror = "1.0"
anyhow = "1.0"
tokio = { version = "1.5.0", features = ["net", "rt"] }
parking_lot = "0.11.1"

# socks5
socks5-protocol = "0.3.2"

# http
http = { version = "0.2.4", optional = true }
# hyper = { version = "0.14.7", features = ["http1", "client", "server"] }
hyper = { git = "https://github.com/hyperium/hyper", version = "0.14.11", features = ["http1", "client", "server"], rev = "39b6d01aa0e520077bb25e16811f5ece00a224d6" }

# transparent
libc = "0.2.91"
socket2 = "0.4.0"
cfg-if = "1.0"

# rule
smoltcp = "0.7.0"
lru_time_cache = "0.11"
serde_with = "1.8.1"
maxminddb = "0.18.0"
flate2 = "1.0.20"
tar = "0.4.35"
once_cell = "1.7.2"

[features]
default = ["http_server"]
plugin = []
http_server = []
