[package]
name = "rd-std"
version = "0.1.0"
authors = ["spacemeowx2 <spacemeowx2@gmail.com>"]
edition = "2018"
description = "std for rabbit-digger"
license = "MIT OR Apache-2.0"

[dependencies]
# common
rd-interface = { version = "0.4", path = "../rd-interface" }
rd-derive = { version = "0.1", path = "../rd-derive" }
futures = "0.3"
serde = "1.0"
serde_derive = "1.0"
log = "0.4"
thiserror = "1.0"
anyhow = "1.0"
tokio = { version = "1.5.0", features = ["net", "rt"] }

# socks5
socks5-protocol = "0.3.2"

# http
http = { version = "0.2.4", optional = true }

# redir
libc = "0.2.91"
socket2 = "0.4.0"

[features]
default = ["http_server"]
plugin = []
http_server = []
