[package]
name = "rabbit-digger"
version = "0.1.0"
authors = ["spacemeowx2 <spacemeowx2@gmail.com>"]
edition = "2018"
description = "Just a stub"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.38"
rd-interface = { path = "./rd-interface", version = "0.3" }
futures = "0.3.5"
libloading = "0.6.7"
serde = "1.0.119"
serde_derive = "1.0.119"
serde_with = "1.8.1"
async-std = { version = "1.9", features = ["attributes", "unstable"] }
structopt = { version = "0.3.21", features = ["paw"] }
paw = "1.0.0"
log = { version = "0.4.13", features = ["release_max_level_debug"] }
env_logger = "0.8.2"
dotenv = "0.15.0"
serde_yaml = "0.8.15"
serde_json = "1.0"
pin-project-lite = "0.2.6"
smoltcp = "0.7.0"
uuid = { version = "0.8.2", features = [ "v4" ] }
async-trait = "0.1.42"
once_cell = "1.7.2"
topological-sort = "0.1"
lru_time_cache = "0.11"
rd-socks5 = { path = "./rd-socks5", optional = true }
rd-redir = { path = "./rd-redir", optional = true }

[features]
default = [ "with_plugins" ]
local_log = []

disable_plugins = []
with_plugins = [ "rd-socks5", "rd-redir" ]

[workspace]
members = [
    "rd-interface",
    "rd-socks5",
    "rd-redir",
]

[profile.release]
lto = true
codegen-units = 1
panic = 'abort'
