[package]
name = "rabbit-digger"
version = "0.1.0"
authors = ["spacemeowx2 <spacemeowx2@gmail.com>"]
edition = "2018"
description = "Just a stub"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.38"
rd-interface = { path = "./rd-interface", version = "0.1" }
futures = "0.3.5"
libloading = "0.6.7"
serde = "1.0.119"
serde_derive = "1.0.119"
async-std = { version = "1.9", features = ["attributes"] }
serde_json = "1.0"
structopt = { version = "0.3.21", features = ["paw"] }
paw = "1.0.0"
log = "0.4.13"
env_logger = "0.8.2"
dotenv = "0.15.0"
serde_yaml = "0.8.15"
pin-project-lite = "0.2.6"

[workspace]
members = [
    "rd-interface",
    "rd-local",
    "rd-socks5",
]
