[package]
name = "rabbit-digger"
version = "0.1.1"
authors = ["spacemeowx2 <spacemeowx2@gmail.com>"]
edition = "2018"
description = "Just a stub"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.38"
rd-interface = { path = "./rd-interface", version = "0.4" }
rd-std = { path = "./rd-std", version = "0.1", optional = true }
futures = "0.3.5"
serde = { version = "1.0.119", features = ["rc"] }
serde_with = "1.8.1"
tokio = { version = "1.5.0", features = ["full"] }
structopt = { version = "0.3.21", default-features = false, features = ["paw"] }
paw = "1.0.0"
tracing = "0.1.26"
tracing-subscriber = { version = "0.2.18", optional = true }
dotenv = "0.15.0"
serde_yaml = "0.8.15"
serde_json = "1.0"
smoltcp = "0.7.0"
uuid = { version = "0.8.2", features = [ "v4", "serde" ] }
topological-sort = "0.1"
lru_time_cache = "0.11"
parking_lot = "0.11.1"

[dev-dependencies]
rusty-hook = "0.11.0"
tokio = { version = "1.5.0", features = ["macros"] }

[features]
default = [ "rd-std" ]

[workspace]
members = [
    "rd-interface",
    "rd-std",
    "rd-derive",
]

[profile.release]
lto = true
codegen-units = 1
panic = 'abort'

[[bin]]
name = "rabbit-digger"
required-features = ["tracing-subscriber"]
