plugin_path: target/debug
net:
  - name: socks5
    type: socks5
    address: 127.0.0.1
    port: 10800
    chain: local
server:
  - name: socks server
    type: socks5
    address: 127.0.0.1
    port: 10888
    net: rule
rule:
  - type: domain
    target: socks5
    domain: twitter.com
  - type: any
    target: local
