[package]
name = "rd-local"
version = "0.1.0"
authors = ["spacemeowx2 <spacemeowx2@gmail.com>"]
edition = "2018"

[dependencies]
rd-interface = { path = "../rd-interface" }
async-std = { version = "1.9" }

[lib]
crate-type = ["dylib"]
