[package]
name = "rd-socks5"
version = "0.1.0"
authors = ["spacemeowx2 <spacemeowx2@gmail.com>"]
edition = "2018"

[dependencies]
rd-interface = { path = "../rd-interface" }
futures = "0.3"
serde = "1.0"
serde_derive = "1.0"

[lib]
crate-type = ["dylib"]
